---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - block:
      - name: Include file main.yml
        include_tasks:
          file: roles/hello_world/tasks/main.yml

      - name: Debugging -- Print the variable var_hw
        debug:
          msg:
            - "{{var_hw}}"

      - name: Debugging -- Print the variable var_hw2
        debug:
          var: var_hw2

    - block:
      - name: Command Uptime
        shell: /usr/bin/uptime
        register: result

      - name: Command Result Uptime
        debug:
          msg:
            - "{{ result.changed }}"
            - "{{ result.stdout }}"
