---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    s1: "Abc,Efg"
  tasks:
    - debug:
        var: s1

    - block:
      - name: Block 1 --- Include file main.yml
        include_tasks:
          file: roles/hello_world/tasks/main.yml

      - name: Debugging -- Print the variable in vars,yml
        debug:
          msg:
            - "var_hw: {{ var_hw }}"
            - "listjojo: {{ listjojo.split() }}"
            - "listjojo: {{ listjojo | split() }}"
            - "listjojocomma: {{ listjojocomma }}"

      - name: Debugging -- Print the variable var_hw2
        debug:
          var: var_hw2

    - block:
      - name: Block 2 --- Command Uptime
        shell: /usr/bin/uptime
        register: result

      - debug:
          msg:
            - "{{ result.changed }}"
            - "{{ result.stdout }}"

    - block:
        - name: Block 3 --- With Items Test
          debug:
            msg: "An item: {{ item }}"
          with_items:
            - 1
            - 2
            - 3

    - block:
        - name: Block 4 --- Obtain the stats of file
          stat:
            path: ./vars.yml
          register: st

        - debug:
            msg: "{{ st }}"
