import os
import sys
import json
import subprocess

def format_tools(data, title):
    out = f"## {title}\n\n"
    if not data or "tools" not in data:
        return out + "No tools found.\n\n"
    for tool in data["tools"]:
        out += f"### `{tool['name']}`\n"
        out += f"{tool.get('description', '')}\n\n"
        if "inputSchema" in tool:
            out += "```json\n"
            out += json.dumps(tool["inputSchema"], indent=2) + "\n"
            out += "```\n\n"
    return out

def fetch_tools(service):
    print(f"Fetching tools for {service}...", file=sys.stderr)
    wrapper_script = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'mcp_wrapper.py')
    env = os.environ.copy()
    env["MCP_NO_AUTO_GEN"] = "1"
    try:
        result = subprocess.run(
            [sys.executable, wrapper_script, service, 'list'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, check=True, env=env
        )
        return json.loads(result.stdout)
    except Exception as e:
        print(f"Error fetching tools for {service}: {e}", file=sys.stderr)
        if hasattr(e, 'stderr') and e.stderr:
            print(f"Stderr: {e.stderr}", file=sys.stderr)
        return None

def main():
    github_data = fetch_tools('github')
    atlassian_data = fetch_tools('atlassian')
    
    output_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'AVAILABLE_TOOLS.md')
    
    with open(output_file, 'w') as f:
        f.write("# GitJira Available Tools\n\n")
        f.write("This file is automatically generated. Do not edit manually.\n\n")
        f.write(format_tools(github_data, "GitHub Tools"))
        f.write(format_tools(atlassian_data, "Atlassian Tools (Jira & Confluence)"))
    
    print(f"Successfully generated {output_file}", file=sys.stderr)

if __name__ == "__main__":
    main()
